import java.nio.file.Files
import java.nio.file.Paths

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */
// Задача для всех подмодулей
subprojects {
    tasks {
        copy {
            from("$rootDir/common-configs/application-keycloak.yaml") // Копируем из корня проекта конфигурационный файл Keycloak
            from("$rootDir/common-configs/application-keycloak-secrets.yaml") // Аналогично вышеупомянутой инструкции
            into("src/main/resources") // Во все директории ресурсов всех подмодулей
        }
    }
}
