logging:
  level:
    root: info
server:
  port: 8084
spring:
  application:
    name: transaction-service
  profiles:
    active:
      - dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/payment-system
            token-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: transaction-service
            client-secret: VQHOlxhSlKxAVbcfJWi1ewULWhYiY3wf
            admin-id: payment-system-admin-cli
            admin-secret: RGybolPwVl7FMtZDyZCn6owhkY3ewtam
  kafka:
    bootstrapServers:
      - localhost:29092
      - localhost:39092
      - localhost:49092
    listener:
      ack-mode: RECORD
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: transaction-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "aq.project.messages"
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # OTEL collector URI
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: transaction-service
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
resilience4j:
  bulkhead:
    instances:
      create-deposit-transaction-bulkhead:
        max-concurrent-calls: 100
      get-deposit-transaction-status-bulkhead:
        max-concurrent-calls: 100

      create-withdraw-transaction-bulkhead:
        max-concurrent-calls: 100
      get-withdraw-transaction-status-bulkhead:
        max-concurrent-calls: 100

      create-transfer-transaction-bulkhead:
        max-concurrent-calls: 100
      get-transfer-transaction-status-bulkhead:
        max-concurrent-calls: 100

  ratelimiter:
    instances:
      create-deposit-transaction-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100
      get-deposit-transaction-status-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100

      create-withdraw-transaction-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100
      get-withdraw-transaction-status-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100

      create-transfer-transaction-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100
      get-transfer-transaction-status-rate-limiter:
        limit-refresh-period: 1s
        limit-for-period: 100

otel:
  instrumentation:
    annotations:
      enabled: true
service:
  keycloak:
    uri: http://localhost:8080
    endpoints:
      token: /realms/payment-system/protocol/openid-connect/token
  kafka:
    backoff:
      max-attempts: 3
      wait-duration: 1500
      multiplier: 2
    services:
      wallet-service:
        topics:
          - wallet_service_create_deposit_transaction_request
          - wallet_service_create_deposit_transaction_response
          - wallet_service_create_deposit_transaction_response_exceptions
          - wallet_service_fail_deposit_transaction_request
          - wallet_service_cancel_deposit_transaction_request # <- end of list deposit transaction topics
          - wallet_service_create_withdraw_transaction_request
          - wallet_service_create_withdraw_transaction_response
          - wallet_service_create_withdraw_transaction_response_exceptions
          - wallet_service_fail_withdraw_transaction_request
          - wallet_service_cancel_withdraw_transaction_request # <- end of list withdraw transaction topics
          - wallet_service_create_transfer_transaction_request
          - wallet_service_create_transfer_transaction_response
          - wallet_service_create_transfer_transaction_response_exceptions
          - wallet_service_fail_transfer_transaction_request
          - wallet_service_cancel_transfer_transaction_request # <- end of list transfer transaction topics
      payment-provider-service:
        topics:
          - payment_provider_service_create_transaction_request
          - payment_provider_service_fail_transaction_request
          - payment_provider_service_cancel_transaction_request
          - payment_provider_service_create_transaction_response
          - payment_provider_service_create_transaction_response_exceptions
  wallet-service:
    name: wallet-service
    uri: http://localhost:8083
    endpoints:
      get-transaction-status: /api/v1/transaction/status
  payment-provider-service:
    name: payment-provider-service
    uri: http://localhost:8086
  transaction-service:
    merchant-id: transaction-service
    merchant-secret: secret
    schedule:
      send-transaction-request-rate: 30
      handle-create-transaction-on-payment-provider-service: 5
      handle-create-deposit-transaction-on-wallet-service: 5
      handle-create-withdraw-transaction-on-wallet-service: 5
      handle-create-transfer-transaction-on-wallet-service: 5
    retry:
      send-transaction-request-to-message-broker:
        max-attempts: 3