logging:
  level:
    root: info
server:
  port: 8084
spring:
  application:
    name: transaction-service
  profiles:
    active:
      - dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/payment-system
            token-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: transaction-service
            client-secret: VQHOlxhSlKxAVbcfJWi1ewULWhYiY3wf
            admin-id: payment-system-admin-cli
            admin-secret: RGybolPwVl7FMtZDyZCn6owhkY3ewtam
  kafka:
    bootstrapServers:
      - localhost:29092
      - localhost:39092
      - localhost:49092
    listener:
      ack-mode: RECORD
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: transaction-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "aq.project.messages"
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # OTEL collector URI
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: transaction-service
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
resilience4j:
  retry:
    instances:
      send-transaction-request-to-payment-service:
        max-attempts: 3
        wait-duration: 1500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exception-predicate: aq.project.utils.resilence.FallbackExceptionPredicate
      get-transaction-status:
        max-attempts: 3
        wait-duration: 1500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exception-predicate: aq.project.utils.resilence.FallbackExceptionPredicate
      send-cancel-transaction-request-to-payment-service:
        max-attempts: 3
        wait-duration: 1500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exception-predicate: aq.project.utils.resilence.FallbackExceptionPredicate

  bulkhead:
    instances:
      send-transaction-request-to-payment-service:
        max-concurrent-calls: 100
      get-transaction-status:
        max-concurrent-calls: 100
      send-cancel-transaction-request-to-payment-service:
        max-concurrent-calls: 100

  ratelimiter:
    instances:
      send-transaction-request-to-payment-service:
        limit-refresh-period: 1s
        limit-for-period: 100
      get-transaction-status:
        limit-refresh-period: 1s
        limit-for-period: 100
      send-cancel-transaction-request-to-payment-service:
        limit-refresh-period: 1s
        limit-for-period: 100

  circuitbreaker:
    instances:
      send-transaction-request-to-payment-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 50
      get-transaction-status:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 50
      send-cancel-transaction-request-to-payment-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 50

otel:
  instrumentation:
    annotations:
      enabled: true
service:
  keycloak:
    uri: http://localhost:8080
    endpoints:
      token: /realms/payment-system/protocol/openid-connect/token
  kafka:
    topics:
      wallet_operation_response:
        name: wallet_operation_response
      wallet_operation_request:
        name: wallet_operation_request
    partitions:
      deposit:
        name: deposit
      withdraw:
        name: withdraw
      transfer:
        name: transfer
    backoff:
      max-attempts: 3
      wait-duration: 1500
      multiplier: 2
  wallet-service:
    name: wallet-service
    uri: http://localhost:8083
    endpoints:
      get-transaction-status: /api/v1/transaction/status
  payment-provider-service:
    name: payment-provider-service
    uri: http://localhost:8086
  transaction-service:
    merchant-id: transaction-service
    merchant-secret: secret
    schedule:
      send-transaction-request-rate: 30
    retry:
      send-transaction-request-to-message-broker:
        max-attempts: 3