server:
  port: ${SERVICE_PORT}
logging:
  level:
    root: info
    aq.project.service: info
    aq.project.mappers.rate: info
    org.hibernate.orm.results: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_URI}
  metrics:
    tags:
      application: ${SERVICE_NAME}
spring:
  application:
    name: ${SERVICE_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    default-schema: public
    create-schemas: true
    locations: 'classpath:db/migration'
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
application:
  rates:
    provider:
      default:
        code: ${DEFAULT_RATE_PROVIDER_CODE}
        name: ${DEFAULT_RATE_PROVIDER_NAME}
        adjustment-factor: ${DEFAULT_RATE_PROVIDER_ADJUSTMENT_FACTOR}