server:
  port: 8085
spring:
  profiles:
    active:
      - dev
  application:
    name: currency-rate-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: currency-rate-service
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
resilience4j:
  retry:
    instances:
      update-currency-rates:
        max-attempts: 3
        wait-duration: 1500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      update-currency-rates:
        sliding-window-type: TIME_BASED
        sliding-window-size: 86400
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 30s
        slow-call-rate-threshold: 50
application:
  rates:
    provider:
      default:
        code: CBR
        name: 'Central Bank of Russia'
        adjustment-factor: 1.0085
  client:
    frankfurter:
      base-url: 'https://api.frankfurter.dev/v2'
      endpoint:
        rate: '/rate'
        rates: '/rates'
        providers: '/providers'
        provider: '/provider/{code}'
        currencies: '/currencies'
        currency: '/currency/{code}'
  schedlock:
    update-rate-shedlock:
      name: updateRatesSchedLock
      lock-at-least-for: 30s
      lock-at-most-for: 3600s
  scheduler:
    update-rate-scheduler:
      fixed-rate: 3600
