logging:
  level:
    root: info
    org.springframework.security: info
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # OTEL collector URI
spring:
  kafka:
    bootstrapServers:
      - localhost:29092
      - localhost:39092
      - localhost:49092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:local-sharding.yaml?placeholder-type=environment
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
application:
  datasource:
    - jdbc:postgresql://localhost:5455/wallets_db,root,root
    - jdbc:postgresql://localhost:5455/wallets_db,root,root
