logging:
  level:
    org.apache.shardingsphere: debug
    org.springframework.security: trace
server:
  port: ${SERVICE_PORT}
spring:
  application:
    name: ${SERVICE_NAME}
  profiles:
    active:
      - prod-local
  kafka:
    listener:
      ack-mode: RECORD
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Old version
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: ${SERVICE_NAME}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "aq.project.messages"
  #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # Old version
management:
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${SERVICE_NAME}
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
otel:
  instrumentation:
    annotations:
      enabled: true
service:
  kafka:
    topics:
      wallet_operation_response:
        name: wallet_operation_response
        partitions: 3
        replicas: 3
        min_insync_replicas: 2
      wallet_operation_request:
        name: wallet_operation_request
        partitions: 3
        replicas: 3
        min_insync_replicas: 2
    partitions:
      deposit:
        name: deposit
      withdraw:
        name: withdraw
      transfer:
        name: transfer
application:
  services:
    wallet-service:
      name: ${SERVICE_NAME}
      audit:
        db: ${DB_NAME}
        schema: ${DB_AUDIT_SCHEMA_NAME}
        table: ${DB_AUDIT_TABLE}
        column: ${DB_AUDIT_COLUMN}