logging:
  level:
    root: info
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_URI}
spring:
  kafka:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:container-sharding.yaml?placeholder-type=environment
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: validate
application:
  datasource:
    - ${SHARD0_DB_URL},${SHARD0_DB_USERNAME},${SHARD0_DB_PASSWORD}
    - ${SHARD1_DB_URL},${SHARD1_DB_USERNAME},${SHARD1_DB_PASSWORD}