openapi: 3.1.0

info:
  title: transaction-service-api-specification
  description: Common transaction-service API specification. It describes all REST endpoints and DTO objects
  version: 1.0.0

servers:
  - url: http://localhost:8084
  - url: http://transaction-service:8084

paths:
  /transaction/send:
    post:
      security:
        - BearerAuth: []
      operationId: sendTransactionRequest
      tags:
        - Transaction
      summary: Handle incoming transaction request
      parameters:
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Identifier of open telemetry trace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionRequestDTO"
              description: Represents data of transaction request
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UuidDefinition"
          description: Returns ID of requested transaction
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /transaction/status/{id}:
    get:
      security:
        - BearerAuth: []
      operationId: getTransactionStatus
      tags:
        - Transaction
      summary: Get transaction status by given ID
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter is represented a valid UUID that describes a transaction ID
          schema:
            $ref: "#/components/schemas/UuidDefinition"
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Identifier of open telemetry trace
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionStatus"
          description: Returns current status of transaction by given ID
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"

tags:
  - name: Transaction
    description: Describes operations with transactions

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequestResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDTO"
      description: Return DTO in case if parameter of request is not valid or requested data is absent
    InternalServerErrorResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDTO"
      description: Return DTO in case if something went wrong during request handling on service side

  schemas:
    TransactionRequestDTO:
      type: object
      required: [ operationType, amount, currency, timestamp, properties ]
      properties:
        operationType:
          $ref: "#/components/schemas/OperationType"
        amount:
          $ref: "#/components/schemas/AmountDefinition"
        currency:
          $ref: "#/components/schemas/CurrencyCodeDefinition"
        timestamp:
          type: integer
          format: int64
        properties:
          type: object
          additionalProperties:
            type: string

    ErrorDTO:
      type: object
      required: [ http_status, message ]
      properties:
        http_status:
          type: integer
          format: int32
        message:
          type: string

    OperationType:
      enum: [ "DEPOSIT", "WITHDRAW", "TRANSFER" ]

    TransactionStatus:
      enum: [ "PENDING", "COMPLETED", "FAILED" ]

    AmountDefinition:
      type: string
      pattern: '^([1-9][0-9]*|[0]+)\.[0-9][0-9]$'
      description: "Описание шаблона денежных средств в формате: 0.XX или Х.ХХ"

    CurrencyCodeDefinition:
      type: string
      pattern: '^[A-Z]{3}$'
      minLength: 3
      maxLength: 3

    UuidDefinition:
      type: string
      pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'