openapi: 3.1.0

info:
  title: person-service-api-specification
  description: Common person-service API specification. It describes all REST endpoints and DTO objects
  version: 1.0.0

servers:
  - url: http://localhost:8082
  - url: http://person-service:8082


paths:
  /person/create-person:
    post:
      security:
        - BearerAuth: []
      operationId: createPerson
      tags:
        - Person
      summary: Create a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateIndividualDataDTO"
              description: Represents data for creating a new person
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UuidDefinition"
          description: Returns an ID of created person
        400:
          $ref: "#/components/responses/BadRequestResponse"
        409:
          $ref: "#/components/responses/ConflictErrorResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /person/delete-person-by-keycloak-id/{keycloakId}:
    delete:
      security:
        - BearerAuth: []
      operationId: deletePersonByKeycloakId
      tags:
        - Person
      summary: Delete a person by given ID
      parameters:
        - name: keycloakId
          in: path
          required: true
          description: Parameter is represented a valid UUID that describes a person ID
          schema:
            $ref: "#/components/schemas/UuidDefinition"
      responses:
        200:
          description: Returns OK status code if operation was successful
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /person/undo-delete-person-by-keycloak-id:
    post:
      security:
        - BearerAuth: []
      operationId: undoDeletePerson
      tags:
        - Person
      summary: Undo delete of a person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UndoOperationDTO"
              description: Represents data of undo operation
      responses:
        200:
          description: Returns OK status code if operation was successful
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /person/update-person:
    patch:
      security:
        - BearerAuth: []
      operationId: updatePerson
      tags:
        - Person
      summary: Update of a person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateIndividualDataDTO"
              description: Represents data for updating a person
      responses:
        200:
          description: Returns OK status code if operation was successful
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /person/undo-update-person:
    post:
      security:
        - BearerAuth: []
      operationId: undoUpdatePerson
      tags:
        - Person
      summary: Undo update of a person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UndoOperationDTO"
              description: Represents data of undo operation
      responses:
        200:
          description: Returns OK status code if operation was successful
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
  /person/get-person-by-keycloak-id/{keycloakId}:
    get:
      security:
        - BearerAuth: []
      operationId: getPersonByKeycloakId
      tags:
        - Person
      summary: Get person info by given ID
      parameters:
        - name: keycloakId
          in: path
          required: true
          description: Parameter is represented a valid UUID that describes a person ID
          schema:
            $ref: "#/components/schemas/UuidDefinition"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseIndividualDataDTO"
          description: Returns current info of person by given ID
        400:
          $ref: "#/components/responses/BadRequestResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"

tags:
  - name: Person
    description: Describes operations with persons

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ConflictErrorResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDTO"
      description: Return DTO in case if person already exists
    BadRequestResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDTO"
      description: Return DTO in case if parameter of request is not valid or requested data is absent
    InternalServerErrorResponse:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorDTO"
      description: Return DTO in case if something went wrong during request handling on service side

  schemas:
    ResponseIndividualDataDTO:
      type: object
      required: [ first_name, last_name, email, phone_number, passport_number, address ]
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        passport_number:
          type: string
        address:
          $ref: "#/components/schemas/AddressDTO"

    AddressDTO:
      type: object
      required: [ country, state, city, address, zip_code ]
      properties:
        country:
          $ref: "#/components/schemas/CountryDTO"
        state:
          type: string
        city:
          type: string
        address:
          type: string
        zip_code:
          type: string

    CountryDTO:
      type: object
      required: [ name, code ]
      properties:
        name:
          type: string
        code:
          type: string

    CreateIndividualDataDTO:
      type: object
      required: [ first_name, last_name, email, phone_number, passport_number, address ]
      properties:
        keycloak_user_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        passport_number:
          type: string
        active:
          type: boolean
          default: true
        address:
          $ref: "#/components/schemas/AddressDTO"

    UpdateIndividualDataDTO:
      type: object
      required: [ keycloak_user_id, first_name, last_name, phone_number, passport_number, address ]
      properties:
        keycloak_user_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        phone_number:
          type: string
        passport_number:
          type: string
        active:
          type: boolean
          default: true
        address:
          $ref: "#/components/schemas/AddressDTO"

    LoginUserDTO:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    UndoOperationDTO:
      type: object
      required: [ operation, payload ]
      properties:
        id:
          type: string
        operation:
          enum:
            - undo_update_person
            - undo_delete_person
        payload:
          type: object
          additionalProperties:
            type: string

    ErrorDTO:
      type: object
      required: [ http_status, message ]
      properties:
        http_status:
          type: int
        message:
          type: string

    UuidDefinition:
      type: string
      pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
