openapi: 3.1.0

info:
  title: currency-rate-service-api-specification
  description: Common currency-rate-service API specification. It describes all REST endpoints and DTO objects
  version: 1.0.0

servers:
  - url: http://localhost:8085
  - url: http://currency-rate-service:8085

paths:
  /api/v1/currency-rate/get-rate:
    get:
      security:
        - BearerAuth: []
      tags:
        - Rate
      summary: Получить курс между двумя валютами на указанную дату/время
      operationId: getRate
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 3
            example: "USD"
          description: Код исходной валюты (например, "USD")
        - name: to
          in: query
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 3
            example: "EUR"
          description: Код целевой валюты (например, "EUR")
        - name: provider
          in: query
          required: false
          schema:
            type: string
          description: Идентификатор конкретного поставщика данных. Если параметр опущен, возвращается смешанное (усредненное) значение по всем доступным провайдерам.
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Дата курса валюты
          example: "2025-11-22"
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Идентификатор трассировки запроса.
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
          description: JWT доступа к ресурсу
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateResponse'
          description: Курс найден
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Курс не найден
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Ошибка запроса

  /api/v1/currency-rate/get-currencies:
    get:
      security:
        - BearerAuth: []
      tags:
        - Rate
      summary: Получить список поддерживаемых валют
      operationId: getCurrencies
      parameters:
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Идентификатор трассировки запроса open telemetry.
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
          description: JWT доступа к ресурсу
      responses:
        200:
          description: Список валют
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyResponse'

  /api/v1/currency-rate/get-rate-providers:
    get:
      security:
        - BearerAuth: []
      tags:
        - Rate
      summary: Получить список провайдеров курсов валют
      operationId: getRateProviders
      parameters:
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Идентификатор трассировки запроса.
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
          description: JWT доступа к ресурсу
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RateProviderResponse'
          description: Провайдеры

  /api/v1/currency-rate/get-currency-info/{code}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Rate
      summary: Получить информацию по указанной валюте
      operationId: getCurrencyInfo
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          description: Трехбуквенный код валюты
          example: USD
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Идентификатор трассировки запроса
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
          description: JWT доступа к ресурсу
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyResponse'
          description: Информация по валюте

        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Ошибка запроса

  /api/v1/currency-rate/get-rate-provider-info/{code}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Rate
      summary: Получить информацию по указанному поставщику курсов валют
      operationId: getRateProviderInfo
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          description: Код поставщика валют
          example: AMCM
        - name: x-trace-id
          in: header
          required: true
          schema:
            type: string
          description: Идентификатор трассировки запроса
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
          description: JWT доступа к ресурсу
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateProviderResponse'
          description: Информация по поставщику валют
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Ошибка запроса

tags:
  - name: Rate
    description: Describes operations with rates

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorDto:
      type: object
      required: [ http_status, message ]
      properties:
        http_status:
          type: integer
          format: int32
        message:
          type: string

    RateResponse:
      type: object
      properties:
        sourceCode:
          type: string
          description: Код исходной валюты (например, "USD")
        destinationCode:
          type: string
          description: Код целевой валюты (например, "EUR")
        rate:
          type: number
          description: Курс обмена sourceCode→destinationCode
        rateDate:
          type: string
          format: date-time
          description: Дата обменного курса
        providerCode:
          type: string
          description: Код провайдера курса

    CurrencyResponse:
      type: object
      properties:
        code:
          type: string
          description: Трёхбуквенный код валюты (ISO 4217)
        isoCode:
          type: integer
          description: Числовой ISO-код валюты
        description:
          type: string
        active:
          type: boolean
        symbol:
          type: string
          description: Символ валюты (например, $ или €)

    RateProviderResponse:
      type: object
      properties:
        providerCode:
          type: string
        providerName:
          type: string
        description:
          type: string
        date:
          type: string
          format: date-time
        active:
          type: boolean

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: UP