server:
  ssl:
    enabled: false
spring:
  kafka:
    bootstrapServers:
      - localhost:29092
      - localhost:29093
      - localhost:29094
  flyway:
    enabled: false
  datasource:
    username: root
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:payment_provider_service_test_db
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
