openapi: 3.1.0
info:
  title: Payment Service API
  description: Common payment-service API specification. It describes all REST endpoints and DTO objects
  version: 1.0.0

servers:
  - url: http://localhost:8087
  - url: http://payment-service:8087

paths:
  /api/v1/payment/get-payment-methods/{currencyCode}/{countryCode}:
    get:
      summary: Get list of payment methods for described currency code and country code
      security:
        - basicAuth: [ ]
      operationId: getPaymentMethods
      tags:
        - Payment
      parameters:
        - name: currencyCode
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
            minLength: 3
            maxLength: 3
        - name: countryCode
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{2}$'
            minLength: 2
            maxLength: 2
        - name: x-trace-id
          in: header
          required: false
          schema:
            type: string
          description: Identifier of open telemetry trace
      responses:
        200:
          description: List of payment methods for described currency code and country code
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentServicePaymentMethodResponseDto"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        401:
          description: Request is unauthorized or credentials are incorrect

  /api/v1/payment/handle-payment:
    post:
      summary: Handle received payment request
      security:
        - basicAuth: [ ]
      operationId: handlePayment
      tags:
        - Payment
      parameters:
        - name: x-trace-id
          in: header
          required: false
          schema:
            type: string
          description: Identifier of open telemetry trace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentServiceHandlePaymentRequestDto"
      responses:
        200:
          description: Payment response DTO which describes result of handle payment request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentServiceHandlePaymentResponseDto"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
        401:
          description: Request is unauthorized or credentials are incorrect

tags:
  - name: Payment
    description: Describes operations with payments

components:
  schemas:
    PaymentServicePaymentMethodResponseDto:
      type: object
      required: [ id, uid, name, provider_method_type, image_url, description, placeholder, data_type, validation_type, validation_rule, default_value, values_options, traceId ]
      properties:
        id:
          type: integer
          format: int32
        uid:
          type: string
          format: uuid
        name:
          type: string
        provider_method_type:
          type: string
        image_url:
          type: string
        description:
          type: string
        placeholder:
          type: string
        data_type:
          type: string
        validation_type:
          type: string
        validation_rule:
          type: string
        default_value:
          type: string
        values_options:
          type: array
          items:
            type: string
        traceId:
          type: string

    PaymentServiceHandlePaymentRequestDto:
      type: object
      required: [ internalTransactionId, methodId, amount, currencyCode, userFields ]
      properties:
        internalTransactionId:
          type: string
          format: uuid
        methodId:
          type: integer
          format: int32
        amount:
          type: number
          format: decimal
        currencyCode:
          type: string
          pattern: '^[A-Z]{3}$'
          minLength: 3
          maxLength: 3
        userFields:
          type: object
          additionalProperties:
            type: string

    PaymentServiceHandlePaymentResponseDto:
      type: object
      required: [ providerTransactionId, status, traceId ]
      properties:
        providerTransactionId:
          type: string
          format: uuid
        status:
          type: string
        traceId:
          type: string

    ErrorDto:
      type: object
      required: [ http_status, message ]
      properties:
        http_status:
          type: integer
          format: int32
        message:
          type: string
