server:
  port: 18581
logging:
  level:
    root: ${LOG_LEVEL}
spring:
  application:
    name: database-migration-service
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
  flyway:
    enabled: true
    baseline-version: ${FLYWAY_DB_BASELINE_VERSION}
    baseline-on-migrate: true
    create-schemas: true
    locations: ${FLYWAY_MIGRATION_SCRIPT_PATH}
    schemas: ${FLYWAY_DB_SCHEMAS}
#    default-schema: ${FLYWAY_DB_DEFAULT_SCHEMA}

