openapi: 3.1.0

info:
  title: Common DTO specifications
  description: Спецификация DTO, используемых в смежных модулях
  version: 1.0.0

servers:
  - url: http://localhost:8081/v1
  - url: http://localhost:8082/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

#    Response schemas
    TokenResponse:
      $ref: "./components/schemas/response/token-response-schema.yaml"
    UserInfoResponse:
      $ref: "./components/schemas/response/user-info-response-schema.yaml"

#      Event schemas
    CreateUserEvent:
      $ref: "./components/schemas/event/create/create-user-event-schema.yaml"
    UpdateUserEvent:
      $ref: "./components/schemas/event/update/update-user-event-schema.yaml"
    LoginUserEvent:
      $ref: "./components/schemas/event/login/login-user-event-schema.yaml"

#      DTO schemas
    RefreshTokenDTO:
      $ref: "./components/schemas/dto/refresh-token-dto-schema.yaml"
    UndoOperationDTO:
      $ref: "./components/schemas/dto/undo-operation-dto-schema.yaml"
