openapi: 3.1.0

info:
  title: Common DTO specifications
  description: Спецификация DTO, используемых в смежных модулях
  version: 1.0.0

servers:
  - url: http://localhost:8081/v1
  - url: http://localhost:8082/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

#    Response schemas
    IndividualDataResponse:
      $ref: "./components/schemas/response/individual-data-response-schema.yaml"
    TokenResponse:
      $ref: "./components/schemas/response/token-response-schema.yaml"
    UserInfoResponse:
      $ref: "./components/schemas/response/user-info-response-schema.yaml"

#      Request schemas
    CreateUserRequest:
      $ref: "./components/schemas/request/create/create-user-request-schema.yaml"

#      Update schemas
    UpdateUserRequest:
      $ref: "./components/schemas/request/update/update-user-request-schema.yaml"

#      Login schemas
    LoginUserRequest:
      $ref: "./components/schemas/request/login/login-user-request-schema.yaml"

#      Token schemas
    RefreshTokenRequest:
      $ref: "./components/schemas/request/token/refresh-token-request-schema.yaml"