keycloak:
  port: 8080
  server-uri: http://localhost:${keycloak.port}
  issuer-uri: ${keycloak.server-uri}/realms/${keycloak.realm}
  admin-uri: ${keycloak.server-uri}/admin/realms/${keycloak.realm}/users
  realm: payment-system
  admin:
    client_id: payment-system-admin-cli