server:
  port: ${SERVICE_PORT}
spring:
  application:
    name: ${SERVICE_NAME}
  profiles:
    active:
      - ${SERVICE_PROFILE}
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/payment-system
            token-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET}
            admin-id: ${OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_ADMIN_ID}
            admin-secret: ${OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_ADMIN_SECRET}
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # Connect to OTEL collector
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${SERVICE_NAME}
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
application:
  keycloak-service:
    name: ${KEYCLOAK_SERVICE_NAME}
    realm: ${KEYCLOAK_REALM}
    uri: http://localhost:8080
    admin-uri: http://localhost:8080/admin/realms/payment-system/users
    endpoints:
      token: /realms/payment-system/protocol/openid-connect/token
      admin: /admin/realms/payment-system/users
  person-service:
    name: ${PERSON_SERVICE_NAME}
    uri: http://localhost:8082
    endpoints:
      create-person: /api/v1/person/create-person
      delete-person-by-keycloak-id: /api/v1/person/delete-person-by-keycloak-id
      undo-delete-person-by-keycloak-id: /api/v1/person/undo-delete-person-by-keycloak-id
      update-person: /api/v1/person/update-person
      undo-update-person: /api/v1/person/undo-update-person
      get-person-info-by-keycloak-id: /api/v1/person/get-person-by-keycloak-id
  wallet-service:
    name: ${WALLET_SERVICE_NAME}
    uri: http://localhost:8083
    endpoints:
      create-wallet: /api/v1/wallet/create
      get-wallet-info: /api/v1/wallet/info
      get-wallet-currency: /api/v1/wallet/currency
  transaction-service:
    name: ${TRANSACTION_SERVICE_NAME}
    uri: http://localhost:8084
    endpoints:
      get-transaction-status: /api/v1/transaction/status
      send-transaction-request: /api/v1/transaction/send
  currency-rate-service:
    name: ${CURRENCY_RATE_SERVICE_NAME}
    uri: http://localhost:8085
    endpoints:
      get-rate: /api/v1/currency-rate/get-rate
      get-rate-providers: /api/v1/currency-rate/get-rate-providers
      get-rate-provider: /api/v1/currency-rate/get-rate-provider-info
      get-currencies: /api/v1/currency-rate/get-currencies
      get-currency: /api/v1/currency-rate/get-currency-info
  individuals-api:
    endpoints:
#      User service operations:
      create-user: /api/v1/user/create-user
      login-user: /api/v1/user/login-user
      update-user: /api/v1/user/update-user
      delete-user-by-keycloak-id: /api/v1/user/delete-user-by-keycloak-id
      get-user-info: /api/v1/user/get-user-info
#      Token service operations:
      refresh-token: /api/v1/token/refresh-token
#      Currency rate service operations:
      get-rate: /api/v1/currency-rate/get-rate
      get-rate-providers: /api/v1/currency-rate/get-rate-providers
      get-rate-provider: /api/v1/currency-rate/get-rate-provider-info
      get-currencies: /api/v1/currency-rate/get-currencies
      get-currency: /api/v1/currency-rate/get-currency-info
#      Transaction service operations:
      get-transaction-status: /api/v1/transaction/status
      do-transaction: /api/v1/transaction/do-transaction
#      Wallet service operations:
      create-wallet: /api/v1/wallet/create
      get-wallet-info: /api/v1/wallet/info