spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-system
          jwk-set-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/payment-system
            token-uri: http://localhost:8080/realms/payment-system/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            admin-id: ${KEYCLOAK_ADMIN_ID}
            admin-secret: ${KEYCLOAK_ADMIN_SECRET}
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # Connect to OTEL collector
application:
  person-service:
    uri: http://localhost:8082
    endpoints:
      create-person: ${PERSON_SERVICE_CREATE_PERSON_ENDPOINT}
      delete-person-by-keycloak-id: ${PERSON_SERVICE_DELETE_PERSON_ENDPOINT}
      undo-delete-person-by-keycloak-id: ${PERSON_SERVICE_UNDO_DELETE_PERSON_ENDPOINT}
      update-person: ${PERSON_SERVICE_UPDATE_PERSON_ENDPOINT}
      undo-update-person: ${PERSON_SERVICE_UNDO_UPDATE_PERSON_ENDPOINT}
      get-person-info-by-keycloak-id: ${PERSON_SERVICE_GET_PERSON_INFO_ENDPOINT}