server:
  port: 8082

spring:
  application:
    name: person-service

  profiles:
    active:
      - prod

  config:
    import:
      - optional:application-secrets.yaml
      - optional:application-keycloak.yaml
      - optional:application-keycloak-secrets.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.issuer-uri}
          jwk-set-uri: ${application.keycloak.issuer-uri}/protocol/openid-connect/certs

management:
  otlp:
    metrics:
      export:
        enabled: false

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # Connect to OTEL collector

  metrics:
    tags:
      application: person-service

  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health

